formatter: "markdown" # this is required

header-from: docs/HEADER.md

recursive:
  enabled: false
  path: modules
  include-main: true

sections:
  hide: []
  show: []

content: |-
  {{ .Header }}

  ### Usage Example
  ```hcl
  {{ include "./examples/main/main.tf" }}
  ```
  {{ .Inputs }}

  {{ .Outputs }}

output:
  file: "README.md"
  mode: overwrite
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
